# پایه n8n
FROM n8nio/n8n:latest

# دسترسی root برای ساخت دایرکتوری‌ها
USER root

# ساخت دایرکتوری session و scripts
RUN mkdir -p /home/node/sessions /scripts \
    && chown -R node:node /home/node/sessions /scripts

# سوئیچ به کاربر node
USER node
WORKDIR /scripts
